extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_fog_layer5_lights;
extern Lights1 castle_grounds_dl_water_layer1_lights;
extern u8 castle_grounds_dl_clouds_i4[];
extern u8 castle_grounds_dl_water_ci4[];
extern u8 castle_grounds_dl_water_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Fog_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Fog_mesh_layer_5_vtx_0[90];
extern Gfx castle_grounds_dl_Fog_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Platform_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Platform_mesh_layer_1_vtx_0[56];
extern Gfx castle_grounds_dl_Platform_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_fog_layer5[];
extern Gfx mat_revert_castle_grounds_dl_fog_layer5[];
extern Gfx mat_castle_grounds_dl_water_layer1[];
extern Gfx mat_revert_castle_grounds_dl_water_layer1[];
extern Gfx castle_grounds_dl_Fog_mesh_layer_5[];
extern Gfx castle_grounds_dl_Platform_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
