extern const GeoLayout planets_geo[];
extern Lights1 planets_planet_lights;
extern u8 planets_Untitled_ci4[];
extern u8 planets_Untitled_ci4_pal_rgba16[];
extern Vtx planets_Big_mesh_layer_1_vtx_0[184];
extern Gfx planets_Big_mesh_layer_1_tri_0[];
extern Gfx mat_planets_planet[];
extern Gfx mat_revert_planets_planet[];
extern Gfx planets_Big_mesh_layer_1[];
extern Gfx planets_material_revert_render_settings[];
